server:
  port: 8082

spring:
  application:
    name: projet
  datasource:
    url: jdbc:mysql://localhost:3306/projet?serverTimezone=UTC
    username: 'root'
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect