server:
  port: 8083

spring:
  application:
    name: groupe
  datasource:
    url: jdbc:mysql://localhost:3306/groupe?serverTimezone=UTC
    username: 'root'
    password: ''
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  cloud:
    loadbalancer:
      ribbon:
        enable: false